name: Terraform Apply
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  terraform:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: [ubuntu-latest]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2

    defaults:
      run:
        working-directory: terraform
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init	

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      #continue-on-error: true

    - name: Terraform Apply
      id: apply
      run: terraform  apply -no-color -auto-approve
      #continue-on-error: true
